## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Colors configuration -------------------------------------

[colors.primary]
background = "#011826"
foreground = "#EEEEEE"

[colors.normal]
black   = "#152B42"
red     = "#D97E96"
green   = "#498653"
yellow  = "#838649"
blue    = "#496886"
magenta = "#A36584"
cyan    = "#50A6A8"
white   = "#ABB2BF"

[colors.bright]
black   = "#1E3C5A"
red     = "#D97E96"
green   = "#498653"
yellow  = "#838649"
blue    = "#496886"
magenta = "#A36584"
cyan    = "#50A6A8"
white   = "#B5BCC9"
